# Generated by Django 5.0.3 on 2024-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_avatar_user_city_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Телефон"
            ),
        ),
    ]
