# Generated by Django 5.0.3 on 2024-03-15 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useful_habits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feeling",
            name="action_datetime",
        ),
        migrations.AddField(
            model_name="feeling",
            name="action_time",
            field=models.TimeField(
                default=django.utils.timezone.now,
                verbose_name="Данные и время действия",
            ),
        ),
    ]
