# Generated by Django 5.0.3 on 2024-03-15 15:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useful_habits", "0002_remove_feeling_action_datetime_feeling_action_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeling",
            name="time_to_complete",
            field=models.DurationField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.timedelta(seconds=120)
                    )
                ],
                verbose_name="Время завершения",
            ),
        ),
    ]
