# Generated by Django 5.0.3 on 2024-03-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useful_habits", "0003_alter_feeling_time_to_complete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feeling",
            name="nice_feeling",
        ),
        migrations.AddField(
            model_name="habit",
            name="nice_feeling",
            field=models.BooleanField(
                default=False, verbose_name="Признак приятного чувства"
            ),
        ),
    ]
