# Generated by Django 5.0.3 on 2024-03-15 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useful_habits", "0005_habit_last_completed_habit_periodicity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feeling",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="user",
        ),
        migrations.AddField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Признак публичности"),
        ),
        migrations.AddField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
