# Generated by Django 5.0.3 on 2024-03-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useful_habits", "0006_remove_feeling_is_public_remove_habit_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feeling",
            name="action_time",
        ),
    ]
