# Generated by Django 5.0.3 on 2024-03-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useful_habits", "0007_remove_feeling_action_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeling",
            name="nice_feeling",
            field=models.BooleanField(
                default=False, verbose_name="Признак приятного чувства"
            ),
        ),
    ]
