# Generated by Django 5.0.3 on 2024-03-17 16:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useful_habits", "0008_feeling_nice_feeling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeling",
            name="time_to_complete",
            field=models.DurationField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.timedelta(seconds=500)
                    )
                ],
                verbose_name="Время завершения",
            ),
        ),
    ]
